# Generated by Django 3.2.9 on 2022-10-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0002_alter_articulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoventa',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='puestoempleado',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
