# Generated by Django 3.2.9 on 2022-10-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0003_auto_20221027_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoventa',
            name='estado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='puestoempleado',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
