# Generated by Django 3.2.9 on 2022-10-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0004_auto_20221027_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
