# Generated by Django 3.2.9 on 2022-10-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFerrus', '0005_empleado_sueldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envios',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='persona',
        ),
        migrations.AddField(
            model_name='envios',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.empleado'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppFerrus.empleado'),
        ),
    ]
